FROM archlinux:base

# Install dependencies
RUN pacman -Sy && \
    pacman -S --needed --noconfirm coreutils gcc make glibc libx11 libxmu libpng openssl libunistring

RUN useradd -mU -s /bin/bash user
USER user
ENV HOME=/home/user

RUN mkdir -p "$HOME/src"
WORKDIR "$HOME/src"

# Copy the source files
COPY Makefile ./
COPY ./src src

# Build
RUN make clean && make

COPY --chmod=755 ./docker/release/copy_release.sh ./

CMD ["./copy_release.sh"]
