FROM ubuntu:resolute

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install build dependencies
RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates make wget tar xz-utils zstd && apt-get clean -y

WORKDIR /
COPY openwrt-toolchain-25.12.5-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst* ./
RUN if [ ! -f openwrt-toolchain-25.12.5-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst ]; then \
    wget https://downloads.openwrt.org/releases/25.12.5/targets/ramips/mt7621/openwrt-toolchain-25.12.5-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst; fi
RUN if [ "$(sha256sum -b openwrt-toolchain-25.12.5-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst | cut -d ' ' -f 1)" != '04316e081dcaea0394d3a8eca761500c91d7d54e9d49ccb8f855ae257ea4f995' ]; then \
    echo 'openwrt-toolchain-25.12.5-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst hash mismatch'; exit 1; fi
RUN tar --zstd -xf openwrt-toolchain-25.12.5-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst && \
    mv openwrt-toolchain-25.12.5-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-14.3.0_musl /opt/toolchain && \
    rm -rf openwrt-*.tar.zst openwrt-toolchain-*/

ENV PATH="/opt/toolchain/bin:$PATH"
ENV TOOL_PREFIX=mipsel-openwrt-linux-musl
ENV TARGET=mipsel-linux-musl

RUN wget https://ftpmirror.gnu.org/libunistring/libunistring-1.4.2.tar.xz || wget https://ftp.gnu.org/gnu/libunistring/libunistring-1.4.2.tar.xz
RUN if [ "$(sha256sum -b libunistring-1.4.2.tar.xz | cut -d ' ' -f 1)" != '5b46e74377ed7409c5b75e7a96f95377b095623b689d8522620927964a41499c' ]; then \
    echo 'libunistring-1.4.2.tar.xz hash mismatch'; exit 1; fi
RUN tar -xJf libunistring-1.4.2.tar.xz && rm libunistring-1.4.2.tar.xz

WORKDIR /libunistring-1.4.2
RUN ./configure --host="$TARGET" --enable-static --disable-shared --disable-rpath --prefix=/opt/static-deps \
    CC="${TOOL_PREFIX}-gcc" CPP="${TOOL_PREFIX}-cpp" AR="${TOOL_PREFIX}-ar" AS="${TOOL_PREFIX}-as" LD="${TOOL_PREFIX}-ld" NM="${TOOL_PREFIX}-nm" \
    CFLAGS='-march=mips32r2 -mtune=mips32r2 -msoft-float -mabi=32 -Os' \
    && make -j4 \
    && make install

RUN mkdir -p /src
WORKDIR /src

# Copy the source files
COPY Makefile ./
COPY ./src src

# Build
RUN make CC=${TOOL_PREFIX}-gcc EXTRA_CFLAGS='-march=mips32r2 -mtune=mips32r2 -msoft-float -mabi=32' STATIC=1 HEADLESS=1 no_ssl

CMD ["mv", "clip_share_no_ssl", "/dist/"]
