FROM fedora:41

# Install dependencies
RUN dnf install --setopt=install_weak_deps=False -y coreutils gcc make glibc-devel libX11-devel libXmu-devel libpng-devel openssl-devel libunistring-devel

RUN useradd -mU -s /bin/bash user
USER user
ENV HOME=/home/user

RUN mkdir -p "$HOME/src"
WORKDIR "$HOME/src"

# Copy the source files
COPY Makefile ./
COPY ./src src

# Build
RUN make clean && make

COPY --chmod=755 ./docker/release/copy_release.sh ./

CMD ["./copy_release.sh"]
